apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-applier-gcp
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: kube-applier-gcp@{{ .Values.mcProjectId }}.iam.gserviceaccount.com
